COUNTRIES_TYPES = (
    ('bangladesh', 'Bangladesh'),
    ('india', 'India'),
    ('uk', 'UK'),
    ('russia', 'Russia'),
    ('uae', 'UAE'),
    ('korea', 'Korea'),
    ('japan', 'Japan'),
    ('canada', 'Canada'),
    ('america', 'America'),
    ('china', 'China'),
    ('belgium', 'Belgium'),
    ('france', 'France'),
    ('hongkong', 'HongKong'),
    ('italy', 'Italy'),
    ('nederlands', 'Nederlands'),
    ('turkey', 'Turkey'),
    ('pan_african', 'Pan African'),
)